export default {
  ADD_QUESTIONS: 'ADD_QUESTIONS',
  SEARCH_QUESTION: 'SEARCH_QUESTION',
  USER_VOTES: 'USER_VOTES',
  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_QUESTIONS: 'GET_USER_QUESTIONS',
  GET_USER_ANSWERS: 'GET_USER_ANSWERS',
  GET_USER_VALID_ANSWERS: 'GET_USER_VALID_ANSWERS', 
  UPDATE_USER: 'UPDATE_USER',
  ADD_NB_POSTS: 'GET_NB_POSTS',
  ADD_NB_RESPONSES: 'ADD_NB_RESPONSES',
  ADD_NB_USERS: 'ADD_NB_USERS'
}


