export default {
  ADD_QUESTIONS: 'ADD_QUESTIONS',
  SEARCH_QUESTION: 'SEARCH_QUESTION',
  USER_VOTES: 'USER_VOTES',
  ADD_NB_POSTS: 'GET_NB_POSTS',
  ADD_NB_RESPONSES: 'ADD_NB_RESPONSES',
  ADD_NB_USERS: 'ADD_NB_USERS',
  SET_STORAGE: 'SET_STORAGE',
  DELETE_STORAGE: 'DELETE_STORAGE'
}


