export default {
  ADD_QUESTIONS: 'ADD_QUESTIONS',
  SEARCH_QUESTION: 'SEARCH_QUESTION',
  USER_VOTES: 'USER_VOTES',
  ADD_NB_POSTS: 'GET_NB_POSTS',
  ADD_NB_RESPONSES: 'ADD_NB_RESPONSES',
  ADD_NB_USERS: 'ADD_NB_USERS'
}

export const ADD_NB_POSTS = 'ADD_NB_POSTS';
export const ADD_NB_RESPONSES = 'ADD_NB_RESPONSES';
export const ADD_NB_USERS = 'ADD_NB_USERS';
export const ADD_END_DATE_FILTER = 'ADD_END_DATE_FILTER';
export const ADD_START_DATE_FILTER = 'ADD_START_DATE_FILTER';